services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.5}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:${NGINX_VERSION:-1.29}-alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:${REDIS_VERSION:-8.6}-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit:${MAILPIT_VERSION:-v1.22}
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mariadb:${MARIADB_VERSION:-12}
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: